extends: standard
plugins:
  - standard
  - promise
parserOptions:
  ecmaVersion: 6
  sourceType: module
rules:
  semi: ['error', 'always']
  no-undef: 'error'
  no-var: 'error'
  indent: ['error', 4]
  curly: ['error', 'multi-or-nest']
