extends: standard
plugins:
  - standard
  - promise
  - react
env:
  mocha: true
parserOptions:
  ecmaVersion: 6
  sourceType: module
rules:
  react/jsx-uses-vars: [2]
  semi: ['error', 'always']
  no-undef: 'error'
  no-var: 'error'
  indent: ['error', 4, { "SwitchCase": 1 }]
  curly: ['error', 'multi-or-nest']
  no-return-assign: 'off'
  no-trailing-spaces: 'off'
  no-throw-literal: 'off'
