export default {
    'application:exit': 'CmdOrCtrl+Q',
    'application:open-file': 'CmdOrCtrl+O',
    'application:open-repository': 'CmdOrCtrl+R',
    'application:save-file': 'CmdOrCtrl+S',
    'application:close-file': 'CmdOrCtrl+W',
    'git:fetch': 'CmdOrCtrl+Shift+F',
    'editor:bold': 'CmdOrCtrl+B',
    'editor:italic': 'CmdOrCtrl+I',
    'editor:strike-through': 'CmdOrCtrl+T',
    'editor:horizontal-rule': 'CmdOrCtrl+H',
    'editor:link': 'CmdOrCtrl+Shift+L',
    'editor:image': 'CmdOrCtrl+Shift+M',
    'editor:unordered-list': 'CmdOrCtrl+Shift+N',
    'editor:ordered-list': 'CmdOrCtrl+Shift+R',
    'editor:blockquote': 'CmdOrCtrl+Shift+B',
    'editor:table': 'CmdOrCtrl+Shift+T',
    'editor:code': 'CmdOrCtrl+Shift+C',
    'editor:header-1': 'CmdOrCtrl+Shift+H'
};
